---

- hosts: all
  vars:
    MySQL_root_pass: password
  tasks:
  - name: Set MySQL root password before installing
    become: true
    debconf: name='mysql-server' question='mysql-server/root_password' value='{{MySQL_root_pass | quote}}' vtype='password'
  - name: Confirm MySQL root password before installing
    become: true
    debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{MySQL_root_pass | quote}}' vtype='password'
                        
  - name: Install MySQL
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    become: true
    with_items:
    - python-mysqldb
    - mysql-server

  - name: Start the MySQL service
    become: true
    service: 
      name: mysql 
      state: started
      enabled: true
